language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'

branches:
  except:
    - gh-pages

# addons:
#   apt:
#     sources:
#       - rabbitmq-testing
#       - qpid-testing
#     packages:
#       - rabbitmq-server
#       - qpidd

before_install:
  - npm install -g codeclimate-test-reporter
  - sudo add-apt-repository ppa:qpid/testing -y
  - sudo apt-get update -q
  - sudo apt-get install qpidd qpid-tools
  - sudo sh -c 'echo "auth=no" >> /etc/qpid/qpidd.conf'

before_script:
  - sudo /etc/init.d/qpidd restart

  # remove these when we can specify link properties
  - sudo qpid-config add queue test.disposition.queue
  - sudo qpid-config add queue test.streams.queue

script:
  - make coverage

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
